[package]
name = "wiki-md"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
dotenv = "0.13"
image = "0.21"
pulldown-cmark = "0.3"
tera = "0.11"
regex = "1.1"
serde = "1.0"
serde_derive = "1.0"
url = "1.7"
walkdir = "2.2"
