[package]
name = "wiki-md"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2018"

[dependencies]
actix-files = "0.5"
actix-web = "3.0"
dotenv = "0.15"
env_logger = "0.8"
log = "0.4"
image = "0.23"
notify = "4.0"
pulldown-cmark = "0.8"
tera = "1.0"
tera-hot = "0.3"
regex = "1.1"
serde = "1.0"
serde_derive = "1.0"
url = "2.0"
walkdir = "2.2"
