[package]
name = "wiki-md"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2018"

[dependencies]
actix-files = "0.1"
actix-web = "1.0"
dotenv = "0.15"
image = "0.22"
pulldown-cmark = "0.6"
tera = "1.0"
regex = "1.1"
serde = "1.0"
serde_derive = "1.0"
url = "2.0"
walkdir = "2.2"
